version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build: filebeat/
    restart: unless-stopped
    volumes: 
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
    depends_on:
      - elasticsearch
    command: ['filebeat', '-e', '-c', './config/filebeat.yml']

